Basic Launch file
strands-project/strands_navigation pull request #362
Opened 2018-07-20 10:27 UTC by Jailander

as discussed in #361 this PR adds the argument `launch_manager` to topological navigation launch files, this allows the possibility of not launching the map manager, which is useful in multi-robot systems.
Also, this PR creates a basic launch file that doesn't include travel time prediction services or policy execution for simple usage cases.

2018-07-20 11:25 UTC, marc-hanheide requested changes

2018-07-20 11:25 UTC, marc-hanheide commented on topological_navigation/launch/topological_navigation_basic.launch
> +		<param name="wait_reset_bumper_duration" value="$(arg wait_reset_bumper_duration)"/>
I think this basic topo nav shouldn't have these robot specific recoveries

2018-07-20 11:25 UTC, marc-hanheide commented on topological_navigation/launch/topological_navigation_basic.launch
> +	<arg name="wait_reset_bumper_duration" default="0.0"/>
see my other comment. bumper is robot-specific.

2018-07-20 15:08 UTC, Jailander commented on topological_navigation/launch/topological_navigation_basic.launch
> +		<param name="wait_reset_bumper_duration" value="$(arg wait_reset_bumper_duration)"/>
true, I will take a look at how to remove these requirements

2018-07-20 15:08 UTC, Jailander commented on topological_navigation/launch/topological_navigation_basic.launch
> +	<arg name="wait_reset_bumper_duration" default="0.0"/>
(y)

2018-10-07 10:53 UTC, marc-hanheide reviewed
Any progress?

2019-12-11 01:28 UTC, closed without merging